### ISSUE TITLE
SSj.log doesn't like symbols

### ISSUE THREAD

**Issue by postcasio** [spheredev/neosphere#269] opened 2018-07-23 16:39 UTC
Passing a Symbol as the first argument to SSj causes it to throw:

```js
SSj.log(Symbol.for("sphere"));
```

```
GAME CRASH: uncaught JavaScript exception
TypeError: Object doesn't support property or method 'ToString'
```

**Comment by postcasio** [comment] 2018-07-23 16:41
Incidentally, it also does not like to display properties that have keys or values that are symbols:

```js
SSj.log({x: Symbol.for('x')})
SSj.log({[Symbol.for('x')]: 'x'})
```

Both log `{}`. This would be an issue with ChakraCore I imagine. I'm not actually sure what the correct behavior is for JSON.stringifying a symbol.

**Comment by fatcerberus** [comment] 2018-07-23 16:46
This happens because the engine attempts to do string coercion on the value passed in, but Symbols are not normally string coercible.  Confusingly, you can call `.toString()` on them but they are not implicitly covertible, e.g. `symValue + ""` will throw.

I'll see if there's a way around it.

**Comment by fatcerberus** [comment] 2018-07-23 16:55
Regarding `JSON.stringify`, I believe it ignores Symbol properties by design.  Admittedly that's a bit annoying for logging though, so it might be worth having a custom serialization for `SSj.log`.  Something like how Node does it would be nice to implement.

**Comment by postcasio** [comment] 2018-07-23 20:20
Now that I think about it, it makes sense for it to ignore symbol properties since they're supposed to be 'private'. And it must also skip any property/value that can't be represented in JSON.

I think the log function itself should definitely be able to handle logging any possible object though (or at least not crash!)

**Comment by fatcerberus** [comment] 2018-07-23 20:33
Agreed, the error throw isn't ideal.  I'm not sure if it's possible to avoid it in all cases, for example if one were to do:

```js
let obj = { pig: 812, cow: 1208 };
obj.toString = () => { throw new Error("Something blew up"); };
SSj.log(obj);
```

The error would be unavoidable (unless the logging function made a specific effort to catch it).  But that's admittedly kind of an edge case; bottom line is simply logging a symbol shouldn't be a recipe to crash your game. :smile:

*edit:* Actually that probably wouldn't crash since objects are handled as a special case (they are JSON encoded rather than string-coerced).  But I'll leave the code example since it still illustrates the issue well enough.  One could still override `Object.prototype.toString`, after all.

I'll fix the crash, at least, and add a GitHub issue to remind me to implement better logging for objects.

**Comment by fatcerberus** [comment] 2018-08-16 05:05
I'll close this issue since the bug is fixed.  See #270 for the issue to track object logging improvements.

**Closed as completed by fatcerberus** 2018-08-16 05:05 UTC
Labels: bug, Core API
